### ISSUE TITLE
Error on /spleef join (NVM forgot to do something)

### ISSUE THREAD

**Issue by Taki21** [ImagicalCorp/SpleefPE#1]
When i do this command, its saying an unknown error happened while performing this command!
Thanks in Advance!

**Comment by Taki21** [comment]
Oh nvm forgot to do something XD!

**Comment by thebigsmileXD** [comment]
Addworld? Can you still give me the error? And world reset still fails

**Comment by Taki21** [comment]
forgot to do /spleef spawn add . . . 
:)

**Comment by thebigsmileXD** [comment]
Will fix that error. It should say "no lobby found"

**Comment by Taki21** [comment]
Thx!
