### ISSUE TITLE
Teleport

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#10]
When the game starts. Ive always died, fell from a high place.

**Comment by thebigsmileXD** [comment]
Aaaahh.. Well, you have to set the worlds spawn on the most top layer

**Comment by imjayl** [comment]
Ohh. I get it.

**Comment by imjayl** [comment]
Can you make it safespawn ?? So i can make spawn in any place, because i want to put a design on spleef map

**Comment by thebigsmileXD** [comment]
It is

**Comment by imjayl** [comment]
It always fell in a high place

**Comment by imjayl** [comment]
Must   /setworldspawn .. Problem solved! :)

**Comment by thebigsmileXD** [comment]
i see. actually.. set lobby should work, but doesn't. Anyways, rewrite incoming anyways
