### ISSUE TITLE
Not OP

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#12]
Anyone can use the commands, like /spleef spawn add

**Comment by thebigsmileXD** [comment]
Nope.. They can't

**Comment by imjayl** [comment]
I tried to use command on my another phone. Its not op but it can use the commands.

**Comment by thebigsmileXD** [comment]
I see.. i'll check that in my new code

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/SpleefPE See new updates there
