### ISSUE TITLE
winner died

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#13]
Winner teleport to world spawn and died . fell from a high place .
Need to Fix it. :)

Ps: iLike this Spleef Plugin :) it works . but it needs to fix all issue that i have for now. Keep it up

**Comment by thebigsmileXD** [comment]
It also teleports to spawn there, maybe thats the bug?

**Comment by imjayl** [comment]
I dont know if its a bug? .

**Comment by imjayl** [comment]
Can you recode it. And make it getSafeSpawn

**Comment by keithkfng** [comment]
Yeah, why don't YOU recode it... You know it takes time -_-

**Comment by thebigsmileXD** [comment]
Keith, really, shut up. You can't do it either.
And yea, just changed the readme.

**Comment by imjayl** [comment]
I can make it but its not mine :) so please check it agin

**Comment by thebigsmileXD** [comment]
May be fixed.
