### ISSUE TITLE
Ask Only

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#14]
Why is there a record for Players Kill, Death, Win ??

**Comment by thebigsmileXD** [comment]
Why not ;)
You could use the data to display it on your server via livesigns or displaying it on a website (like a top 3)
Should i add a switch to disable this?

**Comment by imjayl** [comment]
Aa. Okay. But i have a KillRate Plugin.

**Comment by imjayl** [comment]
Another question. Is there a time limit when the sleef game start?

**Comment by thebigsmileXD** [comment]
But kill rate won't work on spleef.
And the limit is set in the config.

**Comment by imjayl** [comment]
-
plugin:
  version: 1.0.0
  autoUpdate: false
player-defaults:
  kills: 0
  deaths: 0
  wins: 0
  played: 0
  prefix: ""
lobby-defaults:
  minplayers: 2
  maxplayers: 8
reward-command: money grant {PLAYER} 500
...


There's no Time limit there.
Andi disable pvp on spleef map so i dont need kill/death.
Maybe you can put a codes for disable it?  To prevent getting big files

**Comment by thebigsmileXD** [comment]
i'll check it

**Comment by imjayl** [comment]
Ok thanks. Ill wait for that :)

**Comment by thebigsmileXD** [comment]
Well, there is a limit how many players you need to play.
the timer is always 30 seconds.
