### ISSUE TITLE
Spawn Position

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#15]
Please Fix this. When you join a game you'll spawn in random position but when the game start youll be respawn on 1 position (worldspawn).

**Comment by thebigsmileXD** [comment]
You spawn at world spawn when the arena starts, and you have to set spawns first. Wait for the rewrite

**Comment by imjayl** [comment]
Ok ill wait for that.

**Comment by thebigsmileXD** [comment]
Fixed
