### ISSUE TITLE
Cant add world

### ISSUE THREAD

**Issue by HittmanA** [ImagicalCorp/SpleefPE#3]
It won't let me /spleef addworld Spleef (spleef is world name). I can /mw tp Spleef and it is a valid MW world but it won't let me add it

**Comment by HittmanA** [comment]
oh ok thanks!

**Comment by imjayl** [comment]
/spleef addworld (worldname)  is working on me

**Comment by thebigsmileXD** [comment]
Its addworld? Lol

**Comment by imjayl** [comment]
Yes. I just did it. And look in the codes
