### ISSUE TITLE
cant add spawns

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#4]
It doesnt work on the latest pocketmine version

**Comment by thebigsmileXD** [comment]
Are you in the world? /spleef spawns add <number>

**Comment by imjayl** [comment]
Yes.

**Comment by imjayl** [comment]
It doesnt work :(  what version do you use?

**Comment by thebigsmileXD** [comment]
Theres only one version

**Comment by thebigsmileXD** [comment]
I updated the config

**Comment by thebigsmileXD** [comment]
*readme i mean

**Comment by imjayl** [comment]
/spleef spawn add .. It works now :)
