### ISSUE TITLE
server closed

### ISSUE THREAD

**Issue by MaryVictoria** [ImagicalCorp/SpleefPE#6]
server close when the game end when the player spawn at original spawn..when the player kick or leave the game

**Comment by thebigsmileXD** [comment]
Sorry, may you try to explain a bit further? When exactly does it crash? May you please provide a crash dumb/ the line it crashed?

**Comment by MaryVictoria** [comment]
oh im sory.. its working now.. i try it now.. but one thing say when i spleef join arena i tp to setted spawn but it say no lobbby set for arena

**Comment by thebigsmileXD** [comment]
Oh yea, saw that also on my server. Seems to happen since 0.12. i'll try to rewrite spleef soon

**Comment by MaryVictoria** [comment]
i will send ss to you..i spleed spawn add 2 times at the arena..

**Comment by MaryVictoria** [comment]
again server closed when the player quit the game. i mean quit the server

PocketMine-MP Crash Dump Wed Jan 20 16:21:06 UTC 2016

Error: Call to a member function getName() on null
File: /src/pocketmine/level/Level__32bit
Line: 2734
Type: E_ERROR

Code:
[2725] 		return (int) $this->time;
[2726] 	}
[2727] 
[2728] 	/**
[2729] 	 * Returns the Level name
[2730] 	 *
[2731] 	 * @return string
[2732] 	 */
[2733] 	public function getName(){
[2734] 		return $this->provider->getName();
[2735] 	}
[2736] 
[2737] 	/**
[2738] 	 * Returns the Level folder name
[2739] 	 *
[2740] 	 * @return string
[2741] 	 */
[2742] 	public function getFolderName(){
[2743] 		return $this->folderName;
[2744] 	}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #1266 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-3569041 #1 SMP PREEMPT Fri Dec 12 20:16:40 KST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
Slapper 1.2.8 by jojoe77777 for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
SpleefPE 1.0.0 by thebigsmileXD for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvtv40aS/lcacoAdB6Je1MNW4GANj+cud+OMzvZgFhctjBbZlBiTbIZNWlaC/O/3VXXzIY8T
zM7lhx3sxuxmd3V99a6mfuuVcap6y/F05vuj+dl83u+potBFb/lbrzzkeNW7fri+vf1w2+v3UmWM
3NLclUwSUWohRarSjSpEVGVBGetMbFX5o0zVm1OBQVYlCfZFcUKbhqYIhrkOHlWZxpkaJupJJcP3
9N+HB3+yiUusTfCmt5ws/Onv/V6eVNs46y0jmRjV7wU6VMTYZDGZgd66XJeFKqsiE2/irDwV35S7
2HjfE6TvQArL5rzsdztYYGCfznh6+O23dnjOQ/GtuGVqRpQ7JZgvkQELL/JHbpEdjestf3ccmLKI
s619OXEvh3bo8zCvNkkcvCKo3+yq6TEihyUv9FMcqsL7vllvofmzDjR/XkPzF0fQ/LM/hhbpBIQ7
CM+7CKejP0E4HR8hnE7+COE7PqOLc+q/ijNqFlp406mDBysoCxlA7z/1TkbizelStCa0Xt+p4omk
ExTS7N5Waf5mo3WiZHba+2e/t1WZKmRCNoNVBkyB6ngwD9UTTtlUcRLC9idk9RB0qQONtf5Zvyfz
mFeO/cEYK7cwzWVv9IX/sKGQj0m8oT2DxYAmKhbzsvc+zqpnkehAJjttSuEPRgN/7Pmz+floOhYn
Y3F3sxKr2+vrm9W9eFfE4q0KxHgiJqPleL6cjsR/391jMJ4KWaRPC3KvfJeD8mwwH0ww+lVlANWb
YDiyLx+0qU/GBA9kFhY6DnuNjxmS0XWgM50eLlc/0Mhx3Jnsd6Q4AePnmJFVudOFIfXoTG3wfxI8
y+8nCHDETECQ7u+k+Tvmv74b+248deMpxqCjMrlJFPCURYUAEKoc6OgwvDM6Kt92J1JJsaJmY71W
lnPwsl4foUi0JBGtPtzdf/pw+/4tpvZqY+ISeClkQSo3Mjt80kUSmo4oOpMvReEfi0ImcZUcjiQx
JlF8JSRLbr1OwcCeGVivb+jVF2FB1FZZGSOG3q86aI6m+0cOYrXV4jnCMfl6HN0joZ9jBr4AyVv1
dA/37uqkmXqBYPQCQm/FUeMGUUPcK5ke6cb/emurz1+vO5w4KHf3l7f3H1ddIL1dWeZmORwipOyq
zSDQ6bDlbNjQANhVVaiVKtIu2nbupcLGk2O48+m7d6PRsQX6X6+5B0tvvW446Dz+64hpp407w5YK
MN8lMs9V0UFczxzjnQzOjuH+rH/WakH/en+VsRp7Mnndl3oaB4frMC4vi7KD4Wj6GAjM9GGjSvmA
lPRwMpq+gLW6vpH5jQ6RGz8Lq18JK1epzFMmuV5zMFHgTBblev2Czz8D/KpWW2aHdykqRO9/r7xa
zcj3aphKU+Ll0Tmk9TxRKlpdd9VeT30mrmMBoZzZxFuTosL8x9u/SkRHRFFjOF6+POZSWpUFkABt
fRYXKgOUGbCpMlaUhU9WzUhc6SyKt4JK5XWxzk4+qVD8l8yQ6gXy/uh86U/Fx/srSv1zWmDpeSSu
i3U1GsnF2P5JVnGmD/Z5evmo7ZO6uQKAdl+ui/JiPJqMJzS5BRWYhLoY0SiVz16eyAN4xxKeMrnc
Zx7VSIpru4uZnd/vADqJTXmho4gmrLi9XypVHC501pkqkIHdTKhMUMQ5E2JuwWbNX6rL8LNJxzQ1
JBeZLmBbvBQ8FwcvidMYWCZnNzSZwMS8Kg9lqWqeZJZp1KTKgfJksItRAadIPsZx9BSrvRcCh8Q6
gOZtSaL3XpTE213pllkxyCwGB+ZoLtWbemInizDQRXN8/pTXuOMoioMqKQ8XYxY7l6elLjyjyhLF
tblgCFSeW82yf7ZzRqmws4Tl8e795T1NkXwHuTQGe8KLb/kfQFSl9ox8Uo4FVpjX1VikC4imsQA3
S5VjU2YPDmlC5irI/kXAllqBcSryyWDRShSizWLezQoGLO53yihRI0O5qrj5QGlGXYgsRUCKKcVG
iTgLkgpxCA/iM0chWnc6xc6ICLykaWSk+kLjTWGIpNgUSj6Kg64KR0vEkQC2OIr5BOimgBWjngLh
H9W+ITcMVSShHSP2OvtbKSj8y0KQCFOARcmeHKirpY7F4t7vVCaqfFvIEAQG64xM1RJbrjNxcr9D
1PMSTIGLRGbbCu2zoDaWRebM2qDBsy1B/CsLlbZe7VTgUBxvBAN17FXZYB8/xjkCuBzoYjuk0fA9
lPugo4cf7j48zP1zb/JA+yDGhtBSrBEXt+seHfRpp0h21M2jHAsFdfa21YOaCpkhDZaQG79maTKn
4ANPqmSVInfFgRI7dBUJKzkFYWtX7ZHcw2Pe7Koy1OQy9jaBmLFdnAgSbVRo2bok7xNkqOBEuCZF
PMVS/A/FFizhGOO5N0tB8Z023u2wT5KVGjSCwp1iVSUdIVEZGCFyAQyB0aEvwEpklZDk1L7wwNYG
TLXkrzma1XSAWJCvC5grLIJY3RyEsyMsd7GveduK4eRTDEHrDCYlw1AUyljLIzZha49gRxqURhSl
BOxto0geELr6pZJ897KNn7D2SSaVEm/ckUgPpyBuz0PMVRTnPWhzu1XFEm/p5B8rvrKBO12aQxbc
S/MIiy8e4UADev8RSmD7rEHSql2BBqqCSWC16QsOTMIFMJhsH2JIITVDqZrFgoxIc2mVwXNoCdO+
Y5MBHjhXoZ8RSJE/DgSHTT1rWCOpWnZ+iMhD+bYJntgXcfk3unwqeFeoKCOxFb7YK94AAfQsJiQR
xuA5lEumRN5qUwj76n8kegPBUk0g7LTgzEIxKVVbuTmUYEjcWVZGfHhsSL3W04FpHzNjLGxBycNl
KDdlWC5RDHNBmEIEz5hUhBhRn2jVDzAVG+1WA4cm1yCZ4ZwtM2lT3lKM1hwqOCqXCDUy/Ddnn+qr
P2GeMuf/i3lT6pzPd6Gq4cdRMwIuRTkSUcZxQ2fWLKEemlqu0JDEmtMR+aKhAwMOyI67xt/GOAqh
JiQb4xUe/EFZT+MwrtHhZvBQyI2iwx+J1YoT2TnhCE++bpetOeESDXhf68k2HNEJHyiEUIbj5YPP
FxNsVwVDhLkKKBHai0Di1crY7m0AQJIqNy1Mf+RwmtNXGXKofYt6K4sN9O8FOklsvUge9qpU2ZyI
FbdHuD3w3VRmFafcLhcoRyrYwmm/jgkvjMFZg42rUVTHhrS1soH4YPMdj2ARO10lYcNIjAiyz0TL
OtmtyJlzAJyPRhajOHnHnvBZbGRbsbsbUFGh0zrE0l733utGpY5OAcKp7qUpvGI/nX1UuAe7Kns0
Vt7v2eopIPIkcUatC6ERthbus3sWKECMXeRRDUC1TEuLSNVqdo5yPnd8vtV220v1URKgSslu61Kw
p7hlfwFmTkRegJpeWdTOFuqD6EWTvf+U1DrLVEm6aEo3mEZiM+FGlmgaqBCRVOUiAcKeXFRiB7SF
qXtrg9FGNTmRw81JN3zVb8jxi0NJtPvCG3eMmXIfH+uVNSsIK7O5jSptruVWgBJdaMOdU6Ddi0nH
00D8JxoZiPcCtTAM92r1sY+94GCD+LOPw3Jnozb7d0PeY/JLsXCFQVsyGBZMZ+lAXIbwp51MoiGK
fFvFhAp25g7Ckdb+dNZ1yCY7d2h16qTrZ3I+KoNk0reOTQd/ijNUkYAFs1Fs2pTrP66yVV0ptDU7
FUG0aY9Yv6aCPcs9N+zWZNSYbqrt0hUd34sxFRsus1BVya/ritJwHNuputJcO1UgjbR1ohFD9JRl
BYMZbgMrWsS10HQOrVu7o75B1UUk8Q0ktmPipc68CC4rPIAQS7Ywt8WzW5Yixaut6ycAiG9AiF2Y
HIyUg5I8oo/ISR1Z2Tkewiw/54Z9lFV38uOH++ul4KiL/wUVmqsMzRUTitM84QqW2XMnN+w1Kr48
0laAPgKRxGFlK+KUBE7IakqynMnIpRAKZTYzkRlRs0vzLh05rz+ermOYrYXvyF0J4EYa1TnszRiO
8sopfTHBi/FrL1QZDE7ZaY3qcsHmcE+UqbVyFytCITDZ8yj1W01yE9t2txQIuAui6onCgUz28mAs
bUenY0dH8ZvN6DLVVdZNAMbVbDUTxD5Ro5aB7lfwuBTTP94qC8yGlndL4zjriPH55NXdbF2Zsn3k
RllqGxVRJOILFIpYpIaGqr1W6YQ+G/nu5BOSLtV3MbXLitqv/OCuBlwuagoaDhQR3znWYdGFsahK
eJk2MFWPXDQObCrhFqygfhyGAbK1qH7W1AlZ3zAyJVtJOVZSgmnwv1AGCbRWxo18FvKlXNADBZwf
Wns41gUb6a0M48p0tjk9SMcdO6nd6uyO1qNaoZhE11fuQqxlEK22kvYQvgxqs6BlvG3sat4HnzPv
4t9extyjox+vlNOv289uz/OegbKW4uyrqOU6rxJHzT1TanpBeJ2xT3qQHjFtb+k8tiNDkiRRpojV
JV25uNmxCw90Q7YUtrirVUpfkascxY6t+KxBcvCwhYajBSoL2uUOJKIzGu4lHdRM8pxMNzEs3y5x
l3O2R1/aYETXCfQlW9hZm2OdkVjrdZV8E9zIrj264DmeadLJ0Wy+y+Ms0q0Z0DfopT1y0LnvQyHE
/GU6O6RU5rOHGMjXNIxS3+Jei/Y1Mwxbk0Jut8g+7nKguXahGpG+5z++jsbyQ+TMa/yQvKwps4pf
7oZN2LdLq4Ai81xybitAntV558Loiu4M+RJLJTqnbNUX9EmGLlvAiSvFUJlEqJQVhI38lFGep0Uu
tVakHfhjh4hw3y06NUSFgtOUNsHVAc9RIw3Z1zV980Io+/3+NZEkMdKN1cr1s6R8awdUsIC+Y2JZ
c8OvYOzUKS/FT/ToIcn0uXX+J1G0UbAuQ7q3rQyi7hds01ZfYHM39trlLTe3nMUMVwwEO0UhEYNR
l+I7rPOpzAA/CbrvJtfllNSethR06b2cfLfoz86fx33/2e9Pvht/FyIT26j1hj43BRRhLs5GYgv7
NnY0nZ3y5bZ6LlVGAuGvq1fIQ52fUJAJdYZIB9vmN0h5QEvdwPySxKXy7e88PPurkl/tDz/sDx02
AeqaXfsDJpnAc2TRTtjfWNWjqkiaQRQnJX0JBemx/R4flXnzdpu2zzt4r/06hkU/m+YTKf2iIt24
n+3Ui1ETHvKyRVBKYijswL1bvedT6TkPUMu1ew8AzL8ucU9iNiDuCLnw6NPUZDQb+Xj85gfoLfIX
vpKzMJzN/LPFfDwdzeXZaDKR082Z9BfT6fhsM5mOlPgGJ612JBb+LQUfrE383ArdNetuwZiA3qrI
dZqY5fPO1CwKJCrVKY4dRYtFsDg7m89mONo/n/jKH23OF+dhyOeZXapbERp2LHOMNLbCx+JSP6oM
eaZoZj4p+YiIYAU1mGHmIPkjCX+LJzOIczuaDKa933//P3Jvfxs=
===END CRASH DUMP===

**Comment by thebigsmileXD** [comment]
Also getting getSpawn on null
Thanks for reporting

**Comment by MaryVictoria** [comment]
welcome.. ill wait for the update ^_^

**Comment by HittmanA** [comment]
Any idea of next update? My users absolutely LOVE this plugin, and i would hate to delete it because of crashing.

**Comment by thebigsmileXD** [comment]
Give me time

**Comment by imjayl** [comment]
This is my another issue xD when player quit, the server crash. Hope it'll fix asap.

**Comment by ItzJavaCraft** [comment]
On my server (play.javacraft.tk:19132), when I start the server in the PocketMine-MP App for Android, it will start like normal, load up the plugins and seem to be working fine and when I; or others, try to connect to the server Minecraft displays "Server is closed" and won't let me connect. Has anyone else experienced this? If so - any fixes?

**Comment by thebigsmileXD** [comment]
Thats not related to spleef

**Comment by thebigsmileXD** [comment]
Fixed
