### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#8]
Spleef Game use Shovel to Remove the snow right??

**Comment by thebigsmileXD** [comment]
It does. I'll add a config soon to define the item.

**Comment by imjayl** [comment]
How about the snow on floor ?? It resets every game.

**Comment by imjayl** [comment]
Im excited for the next update :)

**Comment by thebigsmileXD** [comment]
Snow on.. What?
