### ISSUE TITLE
Lobby

### ISSUE THREAD

**Issue by imjayl** [ImagicalCorp/SpleefPE#9]
When i join spleef game, it said that theres no lobby ??

**Comment by thebigsmileXD** [comment]
Read other issues before. Already known issue.

**Comment by imjayl** [comment]
I think there's something wrong?? It always show when i join spleef game and i get irritated .. But its working.. 

Teleportaion failed contact staff
Error: no Lobby set for spleef

**Comment by thebigsmileXD** [comment]
I know.. Already a known bug and i already told you i know this in another issue ;)

**Comment by imjayl** [comment]
Please check it out :)
